### ISSUE TITLE
REP ds -> c

### ISSUE THREAD

**Issue by jose1711** [sk-spell/hunspell-sk#16]
dost casto na forach narazam na slovo "podstivý". `REP ds c` by mohol davat dobre navrhy pri opravach.
pred aplikovanim:
```
podstivý
& podstivý 2 0: pomstivý, podstavcový
```
po aplikovani:
```
podstivý
& podstivý 2 0: poctivý, pomstivý
```

**Comment by zdenop** [comment]
pošli PR.

**Comment by jose1711** [comment]
dik
