### ISSUE TITLE
rozdelit sk-SK.dic na viac suborov

### ISSUE THREAD

**Issue by jose1711** [sk-spell/hunspell-sk#2]
aktualne github nedokaze zobrazit v prehliadaci `sk_SK.dic` - iba jeho aktualnu raw verziu. mozno by bolo fajn rozdelit subor na mensie podla nejakeho kluca, trebars abecedne:
```
sk_SK.dic.a
sk_SK.dic.b
..
sk_SK.dic.z
```

**Comment by zdenop** [comment]
Podľa mňa to vyrobí ďalšie problémy - ja som to voľakedy držal v databáze, lebo potrebuješ pracovať nad celým datasetom (napr. potrebuješ všetky slová, začínajúce/končiance na "xyz", všetky slová, ktoré maj FLAG, ktoré nemajú FLAG...)

**Comment by jose1711** [comment]
Ked je to blbost, tak to zavieram.
