### ISSUE TITLE
aspell: The condition "eňa" does not guarantee that "ň" can always be stripped

### ISSUE THREAD

**Issue by andrewshadura** [sk-spell/hunspell-sk#32]
Keď skúšam použiť slovník s aspell, dáva mi chybu:
```
Error: sk_sk.aff:387: The condition "eňa" does not guarantee that "ň" can always be stripped.
```
cc @jose1711

**Comment by zdenop** [comment]
Ahoj, pokiaľ si dobre pamätám, tak je hunspell slovník je potrebné trochu upraviť, aby išiel s aspellom... Presné detaily si nepamätám - možno by bolo dobré urobiť issue v aspelly, nech nemusíme robiť kompromisy v hunspelly 
Čiže nie je to problém slovníka/definície, ale aspellu ;-)

**Comment by andrewshadura** [comment]
V tomto prípade mi sa to nezdá, lebo možno zle chápem, ako to má fungovať, ale myslím si, že toto pravidlo je zlé:
```
 SFX D   ň           niam       eňa is:dative is:plural 
```

**Comment by andrewshadura** [comment]
Ak ab43f73 revertnem, funguje to bez problémov (až na to, že samotný slovník potrebuje [pár uprav](https://salsa.debian.org/debian/aspell-sk/-/blob/debian/experimental/debian/rules#L13)).

**Comment by andrewshadura** [comment]
Je to chápem tak, že *condition* musí vždy končiť rovnako, ako *suffix*, takže ake je to `ň`, tak to nemôže byť `eňa`.

**Comment by zdenop** [comment]
Máš pravdu - slovo, ktoré sa skloňuje podľa vzoru Dlaň nemôže končiť na "a"

**Comment by zdenop** [comment]
Toto bude asi tiež problém:
```
$ grep a/D sk_SK.dic
Keňa/D po:noun is:feminine
```

**Comment by zdenop** [comment]
vďaka. malo by to byť  vyriešené.

**Comment by andrewshadura** [comment]
Aha, to isté tu:
```
SFX D   eň          ňam        ec is:dative is:plural
```
