### ISSUE TITLE
Chybajuce rozne ohybane slova, sklonovane, stupnovane a pod. v ASCII slovniku

### ISSUE THREAD

**Issue by Dreamer8** [sk-spell/hunspell-sk#41]
Nie som si isty, ci sa niekto este zaobera slovenskym slovnikom bez diakritiky, ASCII, az teraz som nasiel toto forum, takze tu su niektore problemove slova.

Napr. slovo "konspirator" v slovniku je, ale mnozne cislo "konspiratori" sa zobrazuje ako chyba.

Pravidelne sa podobne slova podciarkuju, niektore som uz mozno aj pridal do svojho slovnika, takze teraz nedokazem napisat vsetky, hlavne bezne slova, ale neskor sem pridam viac takych slov.

Nasiel som sposob, ako slova pridat do slovnika, ale neviem ako ich odobrat, resp. ako docasne nepouzivat vlastne pridane slova.

Pouzivam Firefox 99.0.1 (64-bit), Slovenská kontrola preklepov (bez diakritiky) 2.4.1, Windows 10 21H1 64-bit.

**Comment by zdenop** [comment]
Ahoj,
ascii slovniku sa teraz nikto velmi nevenuje...
technicky by nemal byt problem ho vytvorit pregenerovanim z nonascii (ktory sa vyvija), len je potrebne najst niekoho, kto na to spravi skript...  ;-)

**Comment by Dreamer8** [comment]
Dakujem za odpoved, snad sa niekto najde, je to velmi uzitocna vec.

**Comment by Dreamer8** [comment]
Dalsie slovo "rozostup" je v slovniku, ale mnozne cislo "rozostupy" nie, podobne "rozostupov", "rozostupmi".

Nie je moznost, aby uzivatelia podobne chybajuce slova pridavala na nejakej stranke a nasledne by sa tieto slova hromadne pridali do slovnika?

**Comment by zdenop** [comment]
Skus toto (zip v nazve zmen na xpi)
[2.4.5-sk2@dictionaries.addons.mozilla.org.zip](https://github.com/sk-spell/hunspell-sk/files/8609662/2.4.5-sk2%40dictionaries.addons.mozilla.org.zip)

**Comment by Dreamer8** [comment]
> Skus toto (zip v nazve zmen na xpi) [2.4.5-sk2@dictionaries.addons.mozilla.org.zip](https://github.com/sk-spell/hunspell-sk/files/8609662/2.4.5-sk2%40dictionaries.addons.mozilla.org.zip)

O co konkretne ide, aktualizovana verzia?

**Comment by zdenop** [comment]
ano

**Comment by Dreamer8** [comment]
Dakujem, ale po nainstalovani mi Firefox mrzne, kdekolvek je pole pre pisanie, napr. tu alebo na phpBB forach, hned po kliknuti Firefox prestane reagovat - Not responding, trvalo to niekolko minut, po ukonceni a opakovanom spusteni sa to sprava rovnako, po preinstalovani na starsiu verziu 2.4.1 vsetko funguje bez problemov.

Mam Firefox 100.0 (64-bit), Windows 10 21H1 64-bit.

**Comment by zdenop** [comment]
pokus cislo 2:
[2.4.5b-sk2@dictionaries.addons.mozilla.org.zip](https://github.com/sk-spell/hunspell-sk/files/8695599/2.4.5b-sk2%40dictionaries.addons.mozilla.org.zip)

**Comment by Dreamer8** [comment]
Dakujem, toto uz funguje dobre, zatial, program nemrzne, budem to nadalej testovat.

**Comment by zdenop** [comment]
Ked neboli zhlasene ziadne problemy, tak som to uploadol:

- https://addons.thunderbird.net/en-US/thunderbird/addon/sk-spell-ascii/
- https://addons.mozilla.org/en-US/firefox/addon/sk-sk-ascii_spellchecking/
