### ISSUE TITLE
nuspell hlási chyby v sk_SK slovníku

### ISSUE THREAD

**Issue by richo67** [sk-spell/hunspell-sk#43]
Nuspell hlási chyby pri použití sk_SK slovníku. Nahlásil som ju na  [chybu v nuspell](https://github.com/nuspell/nuspell/issues/126). Ak si pozriete na odpoveď, tvrdia, že chyba je spôsobená chýbajúcim ```FLAG UTF-8``` ktorý by sa mal pridať hneď za  ```SET UTF-8``` v .aff súbore. 

Základné informácie o tm čo používam.

| key                                       | value |
|-------------------------------------------|-------|
| Operating system, distribution, version = |    Latest Manjaro GNOME 43.1   |
| Nuspell version                         = |    5.1.2   |
| Dictionary, package name, version       = |    sk_SK hunspell 2.4.6 from  https://github.com/sk-spell/hunspell-sk/releases/tag/v2.4.6   |
| Command-line tool or GUI application    = |   command line     |

## Kroky na zreprodukovanie chyby
po nainštalovaní sk_SK aff a dic súborov treba iba spustiť nuspell pre sk_SK
nuspell -d sk_SK

## Chybové hlásenia

Pozrite si chyby v [error.log.gz](https://github.com/nuspell/nuspell/files/10184905/error.log.gz)

**Comment by zdenop** [comment]
nuspell nepoužívam a hunspell chybu nehlási. Pozeral som [dokumentáciu](https://linux.die.net/man/4/hunspell) a nie som si celkom istý, čo spraviť, aby bol nuspell spokojný. 

Môžete prosim vyskúsať zamenit (v `sk_SK.aff`) "`NOSUGGEST ř`" s "`NOSUGGEST ř UTF-8`"? 
A "`SFX č Y 15  #`" s "`SFX č Y 15  UTF-8 #`". Prípadne sa s tým pohrajte s pošli, čo treba zmeniť.

**Comment by zdenop** [comment]
skúste aktuálne dáta - urobil som tam pár zmien.

**Comment by richo67** [comment]
Zdá sa to byť v poriadku už to nehlási žiadnu chybu:

```
nuspell -d sk_SK
INFO: Locale LC_CTYPE=en_GB.UTF-8, Input encoding=UTF-8, Output encoding=UTF-8
INFO: Pointed dictionary /usr/share/hunspell/sk_SK.aff
Enter some text: hruska
& Wrong: hruska. How about: hruška, hrudka, Truska, Pruska

motyl
& Wrong: motyl. How about: motýľ, mytol, motal, metyl, motel
```

Asi ste neurobil to čo spomínal dimztimz v [nuspelly](https://github.com/nuspell/nuspell/issues/126#issuecomment-1342664886) pridať ta ten ```FLAG UTF-8```

Ako ste to opravil?

**Comment by zdenop** [comment]
Podla [hunspell man page](https://manpages.ubuntu.com/manpages/trusty/en/man4/hunspell.4.html) navrhované riešenie (FLAG utf-8) spôsobuje problémy na arm zariadenia (_UTF-8 flag type doesn't work on ARM platform_) - kvôli nuspellu neodpálim podporu mobilných zariadení... 
Tak som zmenil názvy problematických flagov, aby zodpovedali ascii tabuľke po pozíciu 127.

**Comment by richo67** [comment]
Rád by som sa niečomu priučil, ak nevadí opýtam sa tu:

Nie je mi úplne jasná táto zmena, nezmení sa tým nejaké funkcia?

```
< NOSUGGEST ř
---
> NOSUGGEST $
```

Ak správne rozumiem ostatným zmenám tak zmena **č** na **n** v ```SFX``` je iba zmena identifikácie bloku pre definíciu koncoviek, v tomto prípade čísloviek a na funkciu nemá vplyv. Je to tak?

Ďakujem za odpovede.

**Comment by zdenop** [comment]
Úprimne nechápem v čom vidíte problém - ja som iba premenoval affix flagy tak, aby spĺňali požiadavky (t.j. že sú z rozsahu znakov ascii).

**Comment by richo67** [comment]
Žiaden problém nevidím, škoda že sa na môj komentár pozeráte ako na problém. Kedže sa v problematike vytvárania slovníkov nevyznám chcel som sa niečo naučiť.
Prepáčte.
