### ISSUE TITLE
Slovo kľud nie je v slovníku

### ISSUE THREAD

**Issue by richo67** [sk-spell/hunspell-sk#44]
Slovo kľud a od neho odvodené sa nenachádza v slovníku.

```
$ hunspell -d sk_SK
Hunspell 1.7.1
kľud
& kľud 6 0: ľud, kľul, kľuj, kľuč, kľuť, k ľud


```

**Comment by zdenop** [comment]
Slovo [`kľud`](https://slovnik.juls.savba.sk/?w=k%C4%BEud&c=k2fd) nie je spisovné slovo (resp. bolo do 1968) - namiesto neho sa má používať slovo `pokoj`,

**Comment by richo67** [comment]
No neviem, nie som špecialista na Slovenský jazyk. Pozrel som si, predtým než som to tu písal, to slovo v tomto [slovníku](https://slovnik.juls.savba.sk/?w=kľud&s=exact&c=Ud06&cs=&d=kssj4&d=psp&d=ogs&d=sssj&d=orter&d=scs&d=sss&d=peciar&d=ssn&d=hssj&d=bernolak&d=noundb&d=orient&d=locutio&d=obce&d=priezviska&d=un&d=pskfr&d=pskcs&d=psken#) a našiel som ho. 

Píšu tam, ako ste správne poznamenal, že _vhodnejšia_ varianta je pokoj, ale iba vo verejnej komunikácií. Slovo je však stále uverejnené aj v slovníku z roku 2015.
