### ISSUE TITLE
'co' nie je opravené na 'čo'

### ISSUE THREAD

**Issue by richo67** [sk-spell/hunspell-sk#45]
Dobrý deň.
Všimol som si že keď mám v texte niektoré s nasledujúcich slov tak nie sú opravené

```
co   -> čo
cely -> celý
ze   -> že

```
Je to chyba v slovníku alebo niečo iné?

**Comment by zdenop** [comment]
V akom programe? S akou verziu slovenských dát?... 
Bez poskytnutia na reprodukovanie problému vám nikto nepomôže.

**Comment by richo67** [comment]
Posledna verzia slovniku ako je zverejnena tu 2.4.7 a hunspell 1.7.2

**Comment by zdenop** [comment]
`cely` je korektné slovenské slovo - množné číslo od slova `cela` (generované z `cela/z`)

`co` a `ze` boli zadefinované v slovníku, keďže nevidím na to dôvod, tak som ich odstránil ee2324a3bddfa5da98daf3081ec1dc894a81e754.

**Comment by richo67** [comment]
Ďakujem. Budete robiť nový release?
