### ISSUE TITLE
Chybný návrh / oprava pre skloňovanie slova obetište

### ISSUE THREAD

**Issue by MartinHlavna** [sk-spell/hunspell-sk#52]
Dobrý deň,
v projekte [hector](https://github.com/MartinHlavna/hector) využívam hunspell spoločne so slovenským slovníkom pre základnú gramatickú kontrolu.

Slovo "obetište" má v genitíve jednotného čísla tvar "obetišta"

https://www.eduself.sk/slovensky-jazyk/tvary-slova/obeti%C5%A1te

hunspell, však tento tvar označí ako chybný a medzi návrhmi pomocou metódy suggest ponúka tvar obetištťa. Problém som overil aj mimo hectora, pomocou rozšírenia pre firefox (https://addons.mozilla.org/sk/firefox/addon/slovak-spell-checking-dictiona/)

Záznam v slovníku pre slovo:

obetište/S po:noun is:neuter

**Comment by MartinHlavna** [comment]
Trochu som lokálne experimentoval a pomohlo mi doplniť nasledovné pravidlá do .aff

```
SFX S   te          ťa         te is:genitive
SFX S   te          ťu         te is:dative
SFX S   te          ti         te is:locative
SFX S   te          ťom        te is:instrumental
SFX S   ište        íšť        ište is:genitive is:plural
SFX S   te          ťami       te is:instrumental is:plural
```

Pravdepodobne to nie je úplne všeobecné riešenie, ale snáď niekomu skúsenejšiemu s hunspel formátom pomôže k plnohodnotnému riešeniu

**Comment by MartinHlavna** [comment]
Momentálne ešte označuje tvar "obetištami" ako správny, aj keď by malo ísť o chybu. Správny tvar je "obetišťami" - má navyše mäkčeň. To je preto, že ho chytá pravidlo

```
SFX S   e           ami        e is:instrumental is:plural
```

**Comment by zdenop** [comment]
Vďaka za report. Ak sa toho nikto iný nechytí, tak sa na to pozriem cez sviatky.

**Comment by MartinHlavna** [comment]
Vďaka za fix.
