### ISSUE TITLE
Dvojity zapor

### ISSUE THREAD

**Issue by jose1711** [sk-spell/hunspell-sk#7]
urcite nechceme akceptovat/navrhovat slova ako "nenezmyselný, neneochladený" a pod.
```
$ grep '^ne' sk-SK.dic| grep '/.*N.*'            
neaktivovaný/YN
neakumulovaný/YN
neangažovaný/YN
nearomatizovaný/YN
..
```
dokopy 421 prídavných mien.

**Comment by zdenop** [comment]
skús upraviť (sed?) a pls pošli PR
